# Generated by Django 4.0.2 on 2022-03-01 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0007_poetry_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='id',
        ),
        migrations.AddField(
            model_name='poetry',
            name='poetry_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
