# Generated by Django 4.0.2 on 2022-03-01 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0008_remove_poetry_id_remove_quotes_id_poetry_poetry_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetry',
            name='poetry_id',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='quote_id',
        ),
        migrations.AddField(
            model_name='poetry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
