# Generated by Django 4.0.2 on 2022-03-04 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0012_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='specifications',
            field=models.FileField(default=django.utils.timezone.now, upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
