# Generated by Django 4.0.2 on 2022-03-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0013_books_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='specifications',
            new_name='specification',
        ),
    ]
