# Generated by Django 4.0.2 on 2022-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0014_rename_specifications_books_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='specification',
        ),
        migrations.AddField(
            model_name='books',
            name='any_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
