# Generated by Django 4.0.2 on 2022-03-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0002_alter_books_any_file'),
        ('mainbot', '0015_remove_books_specification_books_any_file'),
    ]

    operations = [
    ]
