# Generated by Django 4.0.2 on 2022-02-24 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='download',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
