# Generated by Django 4.0.2 on 2022-02-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0004_books_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='download',
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('eng', 'English'), ('epo', 'Spanish'), ('fre', 'French'), ('tur', 'Turkish'), ('dut', 'Dutch'), ('chi', 'Chinese'), ('por', 'Portuguese'), ('ga', 'Irish'), ('he', 'Hebrew'), ('ind', 'Indonesian'), ('fil', 'Filipino'), ('jpn', 'Japanese'), ('rus', 'Russian'), ('hi', 'Hindi')], max_length=20),
        ),
    ]
