# Generated by Django 4.0.2 on 2022-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0005_remove_books_download_alter_books_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summaries',
            field=models.TextField(null=True),
        ),
    ]
