# Generated by Django 4.0.2 on 2022-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0009_remove_poetry_poetry_id_remove_quotes_quote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='any_file',
            field=models.FileField(blank=True, null=True, upload_to='router_specifications'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
