# Generated by Django 4.0.2 on 2022-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0010_alter_poetry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
