# Generated by Django 4.0.2 on 2022-03-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0002_alter_books_any_file'),
        ('mainbot', '0012_alter_books_image'),
    ]

    operations = [
    ]
