# Generated by Django 4.0.2 on 2022-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0013_merge_20220304_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
