# Generated by Django 4.0.2 on 2022-03-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbot', '0014_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='any_file',
        ),
    ]
